//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DescargaFacturas.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int LogId { get; set; }
        public Nullable<int> ActionId { get; set; }
        public string ActionName { get; set; }
        public Nullable<int> PerformedBy { get; set; }
        public string PerformedByName { get; set; }
        public Nullable<System.DateTime> Performed { get; set; }
        public string SearchText { get; set; }
        public Nullable<int> InvoiceId { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Actions Actions { get; set; }
    }
}
