//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DescargaFacturas.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleXREF
    {
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Users Users { get; set; }
    }
}
